#!/usr/bin/env bash
# Set IFS to ':' to separate fields in /etc/passwd
IFS=":"


while read -r username x userid groupid userdesc homedir shell
do
    echo "The user $username is part of the $groupid gang,"
    echo "lives in $homedir and rides $shell."
    echo -n "USER ID's place is protected by the passcode "

   
    passwd_line=$(grep -E "^$username:" /etc/passwd)
    password=$(echo "$passwd_line" | cut -d':' -f2)

    
    echo "$password,"

    echo "more info about the user here: $userdesc"
    echo
done < /etc/passwd

