#!/usr/bin/env bash
#final one
while :                                            
do                                                 
        echo "I am alive!" >> /tmp/my_process      
        sleep 2                                    
done    
